In [1]:
import numpy as np

In [2]:
# Activation Functions


def sigmoid(z):
    return 1 / (1 + np.exp(-z))


def sigmoid_derivative(z):
    s = sigmoid(z)
    return s * (1 - s)


def relu(z):
    return np.maximum(0, z)


def relu_derivative(z):
    return (z > 0).astype(float)


def tanh(z):
    return np.tanh(z)


def tanh_derivative(z):
    return 1 - np.tanh(z) ** 2

In [6]:
# MLP From Scratch
# Architecture:
# Input -> Hidden1 -> Hidden2 -> Output


class MLP:

    def __init__(
        self,
        input_size,
        hidden1_size,
        hidden2_size,
        output_size
    ):

        np.random.seed(42)

        # Layer 1
        self.W1 = np.random.randn(input_size, hidden1_size) * 0.01
        self.b1 = np.zeros((1, hidden1_size))

        # Layer 2
        self.W2 = np.random.randn(hidden1_size, hidden2_size) * 0.01
        self.b2 = np.zeros((1, hidden2_size))

        # Output Layer
        self.W3 = np.random.randn(hidden2_size, output_size) * 0.01
        self.b3 = np.zeros((1, output_size))


    # Forward Propagation
   

    def forward(self, X):

        # Layer 1
        self.Z1 = np.dot(X, self.W1) + self.b1
        self.A1 = sigmoid(self.Z1)

        # Layer 2
        self.Z2 = np.dot(self.A1, self.W2) + self.b2
        self.A2 = sigmoid(self.Z2)

        # Output Layer
        self.Z3 = np.dot(self.A2, self.W3) + self.b3
        self.Y_hat = sigmoid(self.Z3)

        return self.Y_hat

    
    # Mean Squared Error Loss
    
    def compute_loss(self, Y):

        m = Y.shape[0]

        loss = np.sum((self.Y_hat - Y) ** 2) / (2 * m)

        return loss

   
    # Backpropagation
    

    def backward(self, X, Y):

        m = X.shape[0]

        # Output Layer

        dZ3 = (self.Y_hat - Y) * sigmoid_derivative(self.Z3)

        dW3 = np.dot(self.A2.T, dZ3) / m
        db3 = np.sum(dZ3, axis=0, keepdims=True) / m

        # Hidden Layer 2

        dA2 = np.dot(dZ3, self.W3.T)

        dZ2 = dA2 * sigmoid_derivative(self.Z2)

        dW2 = np.dot(self.A1.T, dZ2) / m
        db2 = np.sum(dZ2, axis=0, keepdims=True) / m

        # Hidden Layer 1

        dA1 = np.dot(dZ2, self.W2.T)

        dZ1 = dA1 * sigmoid_derivative(self.Z1)

        dW1 = np.dot(X.T, dZ1) / m
        db1 = np.sum(dZ1, axis=0, keepdims=True) / m

        gradients = {
            "dW1": dW1,
            "db1": db1,
            "dW2": dW2,
            "db2": db2,
            "dW3": dW3,
            "db3": db3
        }

        return gradients

   
    # Gradient Descent Update
    

    def update_parameters(self, gradients, learning_rate):

        self.W1 -= learning_rate * gradients["dW1"]
        self.b1 -= learning_rate * gradients["db1"]

        self.W2 -= learning_rate * gradients["dW2"]
        self.b2 -= learning_rate * gradients["db2"]

        self.W3 -= learning_rate * gradients["dW3"]
        self.b3 -= learning_rate * gradients["db3"]

   
    # Training
   

    def fit(
        self,
        X,
        Y,
        epochs=10000,
        learning_rate=0.1
    ):

        history = []

        for epoch in range(epochs):

            # Forward
            self.forward(X)

            # Loss
            loss = self.compute_loss(Y)

            # Backward
            gradients = self.backward(X, Y)

            # Update
            self.update_parameters(
                gradients,
                learning_rate
            )

            history.append(loss)

            if epoch % 500 == 0:
                print(
                    f"Epoch {epoch:5d} | Loss = {loss:.6f}"
                )

        return history
     # Predict

    def predict(self, X):

        probabilities = self.forward(X)

        return (probabilities > 0.5).astype(int)

    def predict_proba(self, X):

        return self.forward(X)


In [8]:

# XOR Dataset Example

if __name__ == "__main__":

    X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])

    Y = np.array([
        [0],
        [1],
        [1],
        [0]
    ])

    model = MLP(
        input_size=2,
        hidden1_size=8,
        hidden2_size=4,
        output_size=1
    )

    model.fit(
        X,
        Y,
        epochs=10000,
        learning_rate=0.1
    )

    print("\nPredicted Probabilities:")
    print(model.predict_proba(X))

    print("\nPredicted Classes:")
    print(model.predict(X))

    print("\nActual Labels:")
    print(Y)

Epoch     0 | Loss = 0.125002
Epoch   500 | Loss = 0.125000
Epoch  1000 | Loss = 0.125000
Epoch  1500 | Loss = 0.125000
Epoch  2000 | Loss = 0.125000
Epoch  2500 | Loss = 0.125000
Epoch  3000 | Loss = 0.125000
Epoch  3500 | Loss = 0.125000
Epoch  4000 | Loss = 0.125000
Epoch  4500 | Loss = 0.125000
Epoch  5000 | Loss = 0.125000
Epoch  5500 | Loss = 0.125000
Epoch  6000 | Loss = 0.125000
Epoch  6500 | Loss = 0.125000
Epoch  7000 | Loss = 0.125000
Epoch  7500 | Loss = 0.125000
Epoch  8000 | Loss = 0.125000
Epoch  8500 | Loss = 0.125000
Epoch  9000 | Loss = 0.125000
Epoch  9500 | Loss = 0.125000

Predicted Probabilities:
[[0.50000004]
 [0.50000001]
 [0.49999999]
 [0.49999996]]

Predicted Classes:
[[1]
 [1]
 [0]
 [0]]

Actual Labels:
[[0]
 [1]
 [1]
 [0]]
