In [2]:
import tensorflow as tf

# Matrix
A = tf.constant([
    [1.0, 2.0],
    [3.0, 4.0],
    [5.0, 6.0]
])

# Singular Value Decomposition
S, U, V = tf.linalg.svd(A, full_matrices=False)

print("Matrix A:")
print(A.numpy())

print("\nU Matrix:")
print(U.numpy())

print("\nSingular Values:")
print(S.numpy())

print("\nV Matrix:")
print(V.numpy())

# Reconstruction
Sigma = tf.linalg.diag(S)

A_reconstructed = tf.matmul(
    U,
    tf.matmul(Sigma, tf.transpose(V))
)

print("\nReconstructed Matrix:")
print(A_reconstructed.numpy())

Matrix A:
[[1. 2.]
 [3. 4.]
 [5. 6.]]

U Matrix:
[[ 0.22984776 -0.8834609 ]
 [ 0.52474487 -0.24078292]
 [ 0.81964207  0.40189615]]

Singular Values:
[9.525519   0.51429987]

V Matrix:
[[ 0.61962956  0.78489447]
 [ 0.78489447 -0.61962956]]

Reconstructed Matrix:
[[1.0000013 2.0000002]
 [3.000001  4.000001 ]
 [5.0000014 6.0000014]]
